name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      RUN_INTEGRATION_TESTS: false

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.1'

      - name: Install dependencies
        run: go mod tidy

      - name: Run build
        run: go build ./cmd/main.go

      - name: Run tests
        run: go test -v ./...
